name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true # 'recursive' 'true' or 'false'
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: install old maven version
      run: sudo apt-get install maven
    - name: Build with Maven
      run: mvn clean verify
    - name: get version
      id: vars
      run: echo ::set-output name=version::${GITHUB_REF:11}
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset - Windows
      id: upload-release-asset_win
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./releng/smartgrid.newsimcontrol.rcp.launch/target/products/smartgrid.newsimcontrol.rcp.product-win32.win32.x86_64.zip
        asset_name: win_smartgrid.rcp.product-1.0.0-SNAPSHOT.zip
        asset_content_type: application/zip
    - name: Upload Release Asset - Linux
      id: upload-release-asset_linux
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./releng/smartgrid.newsimcontrol.rcp.launch/target/products/smartgrid.newsimcontrol.rcp.product-linux.gtk.x86_64.zip
        asset_name: linux_smartgrid.rcp.product-1.0.0-SNAPSHOT.zip
        asset_content_type: application/zip
    - name: Upload Release Asset - Mac
      id: upload-release-asset_mac
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./releng/smartgrid.newsimcontrol.rcp.launch/target/products/smartgrid.newsimcontrol.rcp.product-macosx.cocoa.x86_64.zip
        asset_name: mac_smartgrid.rcp.product-1.0.0-SNAPSHOT.zip
        asset_content_type: application/zip
    
